[devops]
15.222.249.138 ansible_user=ubuntu ansible_ssh_private_key_file=~/Documents/college/CDB-3375-FINAL-PROJECT/CDB-3375-final-project.pem

[jenkins]
15.223.204.64 ansible_user=ubuntu ansible_ssh_private_key_file=~/Documents/college/CDB-3375-FINAL-PROJECT/CDB-3375-final-project.pem

[webapp]
15.222.9.36 ansible_user=ubuntu ansible_ssh_private_key_file=~/Documents/college/CDB-3375-FINAL-PROJECT/CDB-3375-final-project.pem

